### ISSUE TITLE
Remove references to deployment BOM

### ISSUE THREAD

**Issue by jamesnetherton** [l2x6/cq-maven-plugin#3]
The deployment BOM was removed from camel-quarkus so the plugin currently fails if you try to use the `cq:create` mojo.

**Comment by ppalaga** [comment]
ouch.

**Comment by ppalaga** [comment]
I am releasing 0.11.0. You may want to watch https://repo1.maven.org/maven2/org/l2x6/cq/cq-maven-plugin/0.11.0/cq-maven-plugin-0.11.0.pom to see when it becomes available in Maven Central.
