### ISSUE TITLE
Evaluate @sync expression in proper order

### ISSUE THREAD

**Issue by jamesnetherton** [l2x6/cq-maven-plugin#84]
Consider this example from camel-quarkus:

```xml
<cxf.version>3.5.3</cxf.version><!-- @sync io.quarkiverse.cxf:quarkus-cxf-parent:${quarkiverse-cxf.version} prop:cxf.version -->
<cxf.xjc-utils.version>3.3.2</cxf.xjc-utils.version><!-- @sync org.apache.cxf:cxf:${cxf.version} prop:cxf.xjc-utils.version -->
```

For this to work properly, you need to run the `sync-versions` mojo twice. Once to update `cfx.version` and then a second time for `cxf.xjc-utils.version` to pick up the new value of `cxf.version`.

It'd be nice the synchronization could work with just one execution.

**Comment by JiriOndrusek** [comment]
That would be really nice. I'm adding a google-bom version sync (in https://github.com/apache/camel-quarkus/pull/4585), which needs to run the `sync-version` mojo 3 times.
